type: raw
name: Test inference for Llama Descendency v0
task: Explain IE Concept
content: |
  <s>[INST]
  What is Infective Endocarditis? Explain the disease to medical students in less than 100 words.
  [/INST]
