type: control
name: Test inference for Clinical Camel v3
task: Explain IE Concept
system: |
  You are a medical teacher who has studied the Infective Endocarditis disease for a long time. From your teaching experience, you distinguish your students through the medical academic degrees.
human: |
  What is Infective Endocarditis? Explain the disease to advanced medical students (5th-year graduation) in less than 100 words.
