type: raw
name: Test inference for MedAlpaca v1
task: Explain IE Concept
content: |
 Question: What is Infective Endocarditis? Explain the disease to advanced medical students (5th-year graduation) in less than 100 words.
 Answer:
