type: raw
name: Test inference Med42 v3
task: Explain IE Concept
content: |
  <|system|>: You are a medical teacher who has studied the Infective Endocarditis disease for a long time. From your teaching experience, you distinguish your students through the medical academic degrees. 
  <|prompter|>: What is Infective Endocarditis? Explain the disease to advanced medical students (5th year) in less than 100 words.
  <|assistant|>: 
