download_status: UNINITIALIZED
experiment_date: 09/03/2024
framework: tf
hf_repo: AdaptLLM/medicine-chat
local: ''
name: Domain Adaptation of Large Language Models
model_params:
  load_in_4bit: False
  load_in_8bit: False
gen_params:
  do_sample:
  - true
  early_stopping:
  - true
  length_penalty:
  - -0.5
  max_new_tokens: 252
  min_new_tokens: 54
  num_beams:
  - 3
  repetition_penalty:
  - 1.2
  temperature:
  - 0.45
  top_k:
  - 100
  top_p:
  - 0.85
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '7'
  task: instruction following
revision: 0ddb624
weightpat: '*.safetensors'
