download_status: COMPLETED
experiment_date: '2024-07-16 14:39:05.527533'
framework: tf
gen_params:
  do_sample: true
  early_stopping: true
  length_penalty: -0.5
  max_new_tokens: 512
  min_new_tokens: 54
  num_beams: 3
  repetition_penalty: 1.2
  temperature: 0.45
  top_k: 100
  top_p: 0.85
hf_repo: ''
local: 'sft-edmcq-v2/checkpoint-43750'
model_params:
  device_map: cuda
  load_in_4bit: false
  load_in_8bit: false
  torch_dtype: bfloat16
name: Checkpoint V2 - Sampling QA pairs
params: null
properties:
  access_space:
  - local, hf_api
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: meditron-7b
  size: '7'
  task: ED_MCQ
revision: null
weightpat: '*.safetensors'
