download_status: UNINITIALIZED
experiment_date: '2024-07-25 15:38:55.136850'
framework: pt
gen_params:
  do_sample: true
  early_stopping: true
  length_penalty: -0.5
  max_new_tokens: 252
  min_new_tokens: 54
  num_beams: 3
  repetition_penalty: 1.2
  temperature: 0.45
  top_k: 100
  top_p: 0.85
hf_repo: wanglab/ClinicalCamel-70B
local: ''
model_params:
  device_map: cuda
  load_in_4bit: true
  load_in_8bit: false
  torch_dtype: bfloat16
name: Clinical Camel
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-70b
  size: '70'
  task: instruction following
revision: 1670df1
weightpat: '*.bin'
