download_status: UNINITIALIZED
experiment_date: 09/03/2024
framework: tf
hf_repo: PORTULAN/gervasio-7b-portuguese-ptpt-decoder
local: ''
name: "Gerv\xE1sio 7B PTPT"
params: null
properties:
  access_space:
  - local, hf_api
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '7'
  task: instruction
revision: 4d3c01e
weightpat: '*.safetensors'
