download_status: COMPLETED
experiment_date: '2024-08-30 17:20:01.462672'
framework: tf
gen_params:
  do_sample:
  - true
  max_new_tokens: 252
hf_repo: meta-llama/Llama-2-7b-chat-hf
local: qa_fixer_model
model_params:
  device_map: cuda
  load_in_4bit: false
  load_in_8bit: false
  torch_dtype: bfloat16
name: Llama-2-7b-chat-hf
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '1.1'
  task: chat
revision: f5db02d
weightpat: '*.safetensors'
