download_status: STARTED
experiment_date: '2024-07-09 11:31:42.422631'
framework: tf
gen_params:
  max_new_tokens: 512
  num_beams: 1
  temperature: 0.65
hf_repo: meta-llama/Llama-2-7b-chat-hf
local: ''
model_params:
  load_in_4bit: false
  load_in_8bit: false
name: Llama-2-7b-chat-hf
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '1.1'
  task: chat
revision: f5db02d
weightpat: '*.safetensors'
