download_status: UNINITIALIZED
experiment_date: '2024-08-28 10:15:53.044548'
framework: tf
gen_params:
  do_sample:
  - false
  early_stopping:
  - false
  - true
  length_penalty:
  - 0.0
  - -0.5
  - -1.0
  max_new_tokens: 252
  min_new_tokens: 54
  num_beams:
  - 1
  - 2
  - 3
  - 5
gen_priorities:
- num_beams
- length_penalty
- early_stopping
- temperature
- top_k
- top_p
- repetition_penalty
hf_repo: meta-llama/Llama-2-70b-chat-hf
local: ''
model_params:
  load_in_4bit: true
  load_in_8bit: false
name: Llama-2-70b-chat-hf
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama2-70b
  size: '70'
  task: chat LLM
revision: e9149a1
weightpat: '*.safetensors'
