download_status: UNINITIALIZED
experiment_date: '2024-07-24 13:51:09.533233'
framework: pt
gen_params:
  do_sample: true
  early_stopping: true
  length_penalty: -0.5
  max_new_tokens: 252
  min_new_tokens: 54
  num_beams: 3
  repetition_penalty: 1.2
  temperature: 0.45
  top_k: 100
  top_p: 0.85
hf_repo: m42-health/med42-70b
local: ''
model_params:
  device_map: cuda
  load_in_4bit: true
  load_in_8bit: false
  torch_dtype: bfloat16
name: Med42 - Clinical Large Language Model
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '70'
  task: instruction
revision: 234f6e3
weightpat: '*.bin'
