download_status: UNINITIALIZED
experiment_date: '2024-08-28 00:24:14.159618'
framework: pt
gen_params:
  do_sample: true
  early_stopping: true
  length_penalty: -0.5
  max_new_tokens: 252
  min_new_tokens: 54
  num_beams: 3
  repetition_penalty: 1.2
  temperature: 0.45
  top_k: 100
  top_p: 0.85
hf_repo: medalpaca/medalpaca-13b
local: ''
model_params:
  device_map: cuda
  load_in_4bit: false
  load_in_8bit: false
  torch_dtype: bfloat16
name: MedAlpaca 13b
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '7'
  task: instruction following
revision: 3e5d80d
weightpat: '*.bin'
