experiment_date: 22/06/2024
hf_repo: epfl-llm/meditron-70b
kwargs:
  max_new_tokens: 200
  repetition_penalty: 1.03
  temperature: 0.01
  top_k: 10
  top_p: 0.95
  typical_p: 0.95
name: Meditron 70B
properties:
  access_space:
  - local
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-70B
  size: '70'
  task: Medical Inference in Text
revision: 3b41343
save_dir: ./storage/current-model
saved: true
