download_status: COMPLETED
experiment_date: '2024-07-20 14:13:02.046770'
framework: tf
gen_params:
  do_sample: true
  early_stopping: true
  length_penalty: -0.5
  max_new_tokens: 512
  min_new_tokens: 54
  num_beams: 3
  repetition_penalty: 1.2
  temperature: 0.45
  top_k: 100
  top_p: 0.85
hf_repo: epfl-llm/meditron-7b
local: 'current-model'
model_params:
  device_map: cuda
  load_in_4bit: false
  load_in_8bit: false
  torch_dtype: bfloat16
name: Meditron Small
params: null
properties:
  access_space:
  - local, hf_api
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '7'
  task: base LLM
revision: d7d0a5e
weightpat: '*.safetensors'
