download_status: UNINITIALIZED
experiment_date: 09/03/2024
framework: tf
hf_repo: epfl-llm/meditron-7b
local: ''
name: Meditron Small
params: null
properties:
  access_space:
  - local, hf_api
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-7b
  size: '7'
  task: base LLM
revision: d7d0a5e
weightpat: '*.safetensors'
