download_status: UNINITIALIZED
experiment_date: 09/03/2024
framework: tf
gen_params:
  max_new_tokens: 512
  temperature: .65
  # top_k: [5, 50, 100]
  # top_p: [0.15, 0.5, 0.75]
  num_beams: 2
  repetition_penalty: [1.0, 1.5, 2.0]
  length_penalty: [-1.0, .0, 1.0]
hf_repo: epfl-llm/meditron-70b
local: ''
model_params:
  load_in_4bit: true
  load_in_8bit: false
name: Meditron-70B-v1.0
properties:
  access_space:
  - local, hf_api
  cost:
  - free in price
  - power consumption
  domain: medical
  predecessor: llama-70b
  size: '70'
  task: base LLM
revision: 3b41343
weightpat: '*.safetensors'
